### ISSUE TITLE
Value of type 'Web3.EIP681Code' has no member 'param'

### ISSUE THREAD

**Issue by fremaksim** [matterinc/DiveLane#23]
![image](https://user-images.githubusercontent.com/16516160/45678004-1817b580-bb68-11e8-9cac-a1e1f04f8b56.png)
it cann't build in xcode 9.4.1, swift 4

**Comment by FesenkoG** [comment]
Hello! Do you still have that problem? Try to clone repo again and switch to the develop branch or just pull the changes, everything should works.
