### ISSUE TITLE
Add link to etherscan from transactions at Transactions Screen

### ISSUE THREAD

**Issue by BaldyAsh** [matterinc/DiveLane#37]
**Current behavior:**
There is just the transactions history list screen now that presents table view with transactions list in it. It's possible to show All, Send, Received, Confirming transactions.

**Expected behavior:**
It would be useful to have possibility to open info about transaction from [etherscan](https://etherscan.io/) in WebView with transaction hash.

**Suggested solution:**
List of transaction is loading in TransactionsHistoryViewController.swift. There is array of transactions:
```swift
var transactions = [[ETHTransactionModel]]()
```
Transaction Model is written in Transaction.swift:
```swift
struct ETHTransactionModel {
    let transactionHash: String
    let from: String
    let to: String
    let amount: String
    let date: Date
    let data: Data?
    let token: ERC20TokenModel? // nil if it is custom ETH transaction
    let networkID: Int64
    var isPending = false
}

struct TransactionInfo {
    var contractAddress: String
    var transactionIntermediate: TransactionIntermediate
    var methodName: String
}

enum TransactionType {
    case custom
    case arbitraryMethodWithParams
}
```

You will need its hash:
```swift
let transactionHash: String
```

You can use in TransactionsHistoryViewController UITableViewDelegate method:
```swift
func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath)
```
The delegate handles rows selections in this method. In other words - tap on row with transaction.
Write in this method code that will open UIWebView with transaction in [etherscan](https://etherscan.io/).
For example, you tapped row of transaction with hash 

> 0x463291e9bb9e97f6611156a407593c77dc86cb4cbc5a7dfbfaaa63c1e5acea7b

You need to open in WebView next URL: 

> https://etherscan.io/tx/0x463291e9bb9e97f6611156a407593c77dc86cb4cbc5a7dfbfaaa63c1e5acea7b

You also need to provide an opportunity to close this view. Just place UIButton with some closing image on top right corner.

It will be great if you implement [UIProgressView](https://developer.apple.com/documentation/uikit/uiprogressview) in this view - to show loading process.

For loading you can use [URLSession](https://developer.apple.com/documentation/foundation/urlsession)

**Acceptance Criteria:**
The code is written in new branch named feature/Etherscan or something like that.
The code implements the targets described above
The code can be merged into the develop branch without conflicts.

**Required Skill:**
Participants needs to have a bit of experience in Swift software development

**Comment by FraDeliro** [comment]
HI @BaldyAsh, I'm working on #38 and if a User select a row in the TransactionsHistoryViewController now will be pushed into the TransactionInfoController, how do you want to manage this? I can take this issue too. Let me Know, thanks ;)

**Comment by BaldyAsh** [comment]
@FraDeliro may be single tap make you goto TransactionInfoController. And long tap opens action view with some extra operations where you place "goto etherscan"
