### ISSUE TITLE
Add transaction info screen

### ISSUE THREAD

**Issue by BaldyAsh** [matterinc/DiveLane#38]
**Current behavior:**
There is just the transactions history list screen now that presents table view with transactions list in it. It's possible to show All, Send, Received, Confirming transactions.

**Expected behavior:**
It would be useful to have possibility to show info about transaction in separate screen.
The info should include following details:
- Hash
- Status (pending/success)
- Direction (in/out)
- From address
- To address
- Amount
- Data
- Network

**Suggested solution:**
List of transaction is loading in TransactionsHistoryViewController.swift. There is array of transactions:
```swift
var transactions = [[ETHTransactionModel]]()
```
Transaction Model is written in Transaction.swift:
```swift
struct ETHTransactionModel {
    let transactionHash: String
    let from: String
    let to: String
    let amount: String
    let date: Date
    let data: Data?
    let token: ERC20TokenModel? // nil if it is custom ETH transaction
    let networkID: Int64
    var isPending = false
}

struct TransactionInfo {
    var contractAddress: String
    var transactionIntermediate: TransactionIntermediate
    var methodName: String
}

enum TransactionType {
    case custom
    case arbitraryMethodWithParams
}
```

This model is already has everything you need to show about transaction.

Firstly: create TransactionInfoController.swift and xib file for it - TransactionInfoController.xib
Build interface that will include labels with transaction info details.

Next: you can use in TransactionsHistoryViewController UITableViewDelegate method:
```swift
func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath)
```
The delegate handles rows selections in this method. In other words - tap on row with transaction.
Write in this method code that will open new TransactionInfoController :
```swift
//Just an example. You need to decide on your own how to init your controller.
guard let indexPathForSelectedRow = tableView.indexPathForSelectedRow else {return}
let cell = tableView.cellForRow(at: indexPathForSelectedRow) as? TransactionCell
guard let selectedCell = cell else {
    return
}
guard let indexPathTapped = tableView.indexPath(for: selectedCell) else { return }
let transaction = transactions[indexPathTapped.row]
let transactionInfoController = TransactionInfoController(transaction: transaction)
self.navigationController?.pushViewController(transactionInfoController, animated: true)
```

**Acceptance Criteria:**
The code is written in new branch named feature/TransationInfoController or something like that.
The code implements the targets described above
The code can be merged into the develop branch without conflicts.

**Required Skill:**
Participants needs to have an experience in Swift software development.

**Comment by FraDeliro** [comment]
If you agree I will take it ;)

**Comment by BaldyAsh** [comment]
@FraDeliro hi! Yes, of course, we appreciate any help 🙌Let's carry the open-source flag together!

**Comment by FraDeliro** [comment]
HI @BaldyAsh, I have almost completed the screen, just one questions before open the PR, where can I find the direction (in or out) info? Thanks.

**Comment by FraDeliro** [comment]
@BaldyAsh  No worries and thank you for your reply ;) Got it 👍

**Comment by BaldyAsh** [comment]
@FraDeliro thank you! Your work is really awesome! Closed
