### ISSUE TITLE
Add Alamofire lib and use it 

### ISSUE THREAD

**Issue by BaldyAsh** [matterinc/DiveLane#40]
**Current behavior:**
Now it is native URLSession used to load some data and interact with APIs.

**Expected behavior:**
Add [Alamofire lib](https://github.com/Alamofire/Alamofire) and rewrite URLSessions with Alamofire.

**Suggested solution:**
You can add Alamofire lib via CocoaPods.
Now only 4 files need to be changed: look at @klymenkoo [comment](https://github.com/matterinc/DiveLane/issues/40#issuecomment-426078063).
All networking should be the separate class, that has functions with required parameters and do all the work by Alamofire.

**Acceptance Criteria:**
The code is written in new branch named feature/Alamofire or something like that.
The code implements the targets described above.
The code can be merged into the develop branch without conflicts.

**Required Skill:**
Participants needs to have a bit of experience in Swift software development.

**Comment by klymenkoo** [comment]
I would love to work on this issue if it is okay. 

As I see 4 files need to be changed: 

<img width="739" alt="screen shot 2018-10-01 at 5 57 08 pm" src="https://user-images.githubusercontent.com/26641473/46318128-72226d00-c5a3-11e8-9539-fb1d3ec17ea6.png">

**Comment by skywinder** [comment]
Hooray  @klymenkoo! welcome to the club! 👍 
That's right, it's just a 4 requests for now. We want to wrap it in a separate class, that will send specialized requests. 
So, in the end, it should be the separate class, that has 4 functions with required parameters and do all the work by Alamofire.

**Comment by klymenkoo** [comment]
@skywinder, sounds good. I'll keep you up to date with my progress.

**Comment by klymenkoo** [comment]
@skywinder I have migrated all `URLSession` requests to `Alamofire`. 

However, I'm a little bit confused with AlamofireWrapper class, how exactly do you see its implementation?

I am not sure if it's beneficial to have a wrapper around _Alamofire_ as each _Alamofire request_ inside `TokenService`, `FiatService`, etc. has its own unique behavior.

**Comment by BaldyAsh** [comment]
@klymenkoo Everything is great 🙌Thank you so much for your work and interest in our project! Hoping to see you again 🔥And have fun Hacktoberfesting 🎃
