### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by klymenkoo** [matterinc/DiveLane#43]
It would be really useful to have **CONTRIBUTING.md** for new developers coming to the project. At the moment, there is the only small section in the README.md, but it only mentions usage of Swiftlint.

I would like to have some kind of guide where I can find how to run the app locally, what sample input data I use to proceed (as I found, I should use "Mnemonics" in "import wallet").

**Comment by BaldyAsh** [comment]
@klymenkoo yes it's very useful. Do you want to make it?

**Comment by klymenkoo** [comment]
@BaldyAsh I'm still new to this project, I feel it would be better if somebody of creators took this issue.
